### PR TITLE
Add multio to dependency_tree.yml and downstream-ci[-hpc].yml

### PR DESCRIPTION
**Pull request by geier1993**

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf-actions/downstream-ci?pullRequest=40) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-actions/downstream-ci?pullRequest=40) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-actions/downstream-ci?pullRequest=40) it.</sub>

**Comment by geier1993** [comment]
Ah, will need to add `clang_build: true`. Let me test

**Comment by geier1993** [comment]
Think it can be merged now

**Comment by figi44** [comment]
@geier1993 Can you link me to a successful workflow run, and could you also please sign the CLA?

**Comment by geier1993** [comment]
yay, successful run with my forked downstream-ci: https://github.com/ecmwf/multio/actions/runs/8998190068/job/24717843393

**Pull request merged**
